name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'bluebluerabbit'
          destination-repository-name: 'Seagull-React'
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
